export const AccessorizeOptions = [
  "Accessories",
  "Background",
  "Ears",
  "Eyes",
  "Hair",
  "Leg",
  "Mouth",
  "Neck",
];

export const StyleOptions = {
  Accessories: [
    { name: "Default", value: "" },
    { name: "Earings", value: "earings" },
    { name: "Flower", value: "flower" },
    { name: "Glasses", value: "glasses" },
    { name: "Headphone", value: "headphone" },
  ],
  Backgrounds: [
    "blue50",
    "blue60",
    "blue70",
    "darkBlue30",
    "darkBlue50",
    "darkBlue70",
    "green50",
    "green60",
    "grey40",
    "grey70",
    "grey80",
    "red50",
    "red60",
    "red70",
    "yellow50",
    "yellow60",
    "yellow70",
  ],
  Ears: [
    { name: "Default", value: "default" },
    { name: "Tilt Backward", value: "tilt-backward" },
    { name: "Tilt Forward", value: "tilt-forward" },
  ],
  Eyes: [
    { name: "Default", value: "default" },
    { name: "Angry", value: "angry" },
    { name: "Naughty", value: "naughty" },
    { name: "Panda", value: "panda" },
    { name: "Smart", value: "smart" },
    { name: "Star", value: "star" },
  ],
  Hair: [
    { name: "Default", value: "default" },
    { name: "Bang", value: "bang" },
    { name: "Curls", value: "curls" },
    { name: "Elegant", value: "elegant" },
    { name: "Fancy", value: "fancy" },
    { name: "Quiff", value: "quiff" },
    { name: "Short", value: "short" },
  ],
  Leg: [
    { name: "Default", value: "default" },
    { name: "Bubble Tea", value: "bubble-tea" },
    { name: "Cookie", value: "cookie" },
    { name: "Game Console", value: "game-console" },
    { name: "Tilt Backward", value: "tilt-backward" },
    { name: "Tilt Forward", value: "tilt-forward" },
  ],
  Mouth: [
    { name: "Default", value: "default" },
    { name: "Astonished", value: "Astonished" },
    { name: "Eating", value: "Eating" },
    { name: "Laugh", value: "Laugh" },
    { name: "Tongue", value: "Tongue" },
  ],
  Neck: [
    { name: "Default", value: "default" },
    { name: "Bend Backward", value: "bend-backward" },
    { name: "Bend Forward", value: "bend-forward" },
    { name: "Thick", value: "thick" },
  ],
};
